# This is required for Continuous Integration for Autoware using the simulator
# and remote update (Over The Air update) to real cars.
# If you have any additional questions, please contact us at #tier4-dev channel.

version: 2

services:
  planning_sim_v2:
    components:
      planning:
        type: roslaunch
        package_name: scenario_test_runner_launch
        file_name: autoware_auto_planning.launch.py
        params:
          vehicle_model: lexus
          sensor_model: aip_xx1
        runtime:
          type: component/standard1/arm64/medium
          cpu: 4
          memory: 8192
      perception:
        type: roslaunch
        package_name: scenario_test_runner_launch
        file_name: autoware_auto_perception.launch.py
        params:
          vehicle_model: lexus
          sensor_model: aip_xx1
        runtime:
          type: component/standard1/arm64/medium
          cpu: 4
          memory: 8192
